-- ============================================================
-- ALUMNI_EVENTS_ORGANIZER_CHAT_6_2
-- Organizer visibility + private temporary event chat.
--
-- IMPORTANT:
-- Apply this to the AlumniConnections Supabase project only
-- AFTER npm run build succeeds.
-- ============================================================

begin;

alter table public.events
  add column if not exists organizer_anonymous boolean not null default false;

create table if not exists public.event_private_chats (
  id uuid primary key default gen_random_uuid(),
  event_id bigint not null references public.events(id) on delete cascade,
  attendee_id uuid not null references public.profiles(id) on delete cascade,
  organizer_id uuid not null references public.profiles(id) on delete cascade,
  expires_at timestamp without time zone not null,
  created_at timestamptz not null default now(),
  constraint event_private_chats_distinct_users
    check (attendee_id <> organizer_id),
  constraint event_private_chats_event_attendee_unique
    unique (event_id, attendee_id)
);

create table if not exists public.event_private_messages (
  id bigint generated by default as identity primary key,
  chat_id uuid not null
    references public.event_private_chats(id) on delete cascade,
  sender_id uuid not null
    references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint event_private_messages_content_length
    check (
      char_length(btrim(content)) between 1 and 2000
    )
);

create index if not exists event_private_chats_event_idx
  on public.event_private_chats(event_id, created_at desc);

create index if not exists event_private_chats_organizer_idx
  on public.event_private_chats(organizer_id, event_id);

create index if not exists event_private_messages_chat_idx
  on public.event_private_messages(chat_id, created_at);

create or replace function public.alumni_prepare_event_private_chat()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $function$
declare
  v_user uuid := (select auth.uid());
  v_organizer uuid;
  v_end timestamp without time zone;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if new.attendee_id is distinct from v_user then
    raise exception 'Invalid attendee';
  end if;

  select
    e.created_by,
    coalesce(e.end_date, e.event_date)
  into
    v_organizer,
    v_end
  from public.events e
  where e.id = new.event_id;

  if v_organizer is null or v_end is null then
    raise exception 'Evento no disponible';
  end if;

  if v_organizer = v_user then
    raise exception 'El organizador no necesita abrir un chat consigo mismo';
  end if;

  if not exists (
    select 1
    from public.event_rsvps r
    where r.event_id = new.event_id
      and r.user_id = v_user
      and r.status in ('interested', 'going')
  ) then
    raise exception 'Marca Me interesa para abrir este chat';
  end if;

  new.organizer_id := v_organizer;
  new.expires_at := v_end + interval '24 hours';

  if timezone('utc', now()) >= new.expires_at then
    raise exception 'Este chat ya expiró';
  end if;

  return new;
end;
$function$;

drop trigger if exists alumni_prepare_event_private_chat
  on public.event_private_chats;

create trigger alumni_prepare_event_private_chat
before insert on public.event_private_chats
for each row
execute function public.alumni_prepare_event_private_chat();

alter table public.event_private_chats
  enable row level security;

alter table public.event_private_messages
  enable row level security;

drop policy if exists event_private_chats_select_participants
  on public.event_private_chats;

create policy event_private_chats_select_participants
on public.event_private_chats
for select
to authenticated
using (
  (
    attendee_id = (select auth.uid())
    or organizer_id = (select auth.uid())
  )
  and timezone('utc', now()) < expires_at
  and public.alumni_users_not_blocked(attendee_id, organizer_id)
);

drop policy if exists event_private_chats_insert_attendee
  on public.event_private_chats;

create policy event_private_chats_insert_attendee
on public.event_private_chats
for insert
to authenticated
with check (
  attendee_id = (select auth.uid())
  and attendee_id <> organizer_id
  and timezone('utc', now()) < expires_at
  and public.alumni_users_not_blocked(attendee_id, organizer_id)
);

drop policy if exists event_private_messages_select_participants
  on public.event_private_messages;

create policy event_private_messages_select_participants
on public.event_private_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.event_private_chats c
    where c.id = event_private_messages.chat_id
      and (
        c.attendee_id = (select auth.uid())
        or c.organizer_id = (select auth.uid())
      )
      and timezone('utc', now()) < c.expires_at
      and public.alumni_users_not_blocked(
        c.attendee_id,
        c.organizer_id
      )
  )
);

drop policy if exists event_private_messages_insert_participants
  on public.event_private_messages;

create policy event_private_messages_insert_participants
on public.event_private_messages
for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.event_private_chats c
    where c.id = event_private_messages.chat_id
      and (
        c.attendee_id = (select auth.uid())
        or c.organizer_id = (select auth.uid())
      )
      and timezone('utc', now()) < c.expires_at
      and public.alumni_users_not_blocked(
        c.attendee_id,
        c.organizer_id
      )
  )
);

grant select, insert
on public.event_private_chats
to authenticated;

grant select, insert
on public.event_private_messages
to authenticated;

grant usage, select
on sequence public.event_private_messages_id_seq
to authenticated;

-- Realtime: Postgres Changes needs the messages table in
-- the supabase_realtime publication.
do $block$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  )
  and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'event_private_messages'
  ) then
    execute
      'alter publication supabase_realtime add table public.event_private_messages';
  end if;
end;
$block$;

-- The row becomes unreadable exactly at expires_at because of RLS.
-- Physical cleanup runs hourly and cascades all messages.
do $block$
declare
  v_job_id bigint;
begin
  select jobid
  into v_job_id
  from cron.job
  where jobname = 'alumni_event_chat_cleanup'
  limit 1;

  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;

  perform cron.schedule(
    'alumni_event_chat_cleanup',
    '17 * * * *',
    'delete from public.event_private_chats where expires_at <= timezone(''utc'', now());'
  );
end;
$block$;

commit;

-- ALUMNI_EVENTS_ORGANIZER_CHAT_6_2:DB

