-- YA APLICADO al proyecto Supabase AlumniConnections.
create table if not exists public.post_moderation_results (
  id bigint generated by default as identity primary key,
  post_id bigint not null unique references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'openai',
  model text not null default 'omni-moderation-latest',
  status text not null default 'pending'
    check (status in ('pending','completed','error')),
  flagged boolean,
  suggested_action text
    check (suggested_action in ('allow','review')),
  top_category text,
  top_score double precision,
  categories jsonb not null default '{}'::jsonb,
  category_scores jsonb not null default '{}'::jsonb,
  category_applied_input_types jsonb not null default '{}'::jsonb,
  raw_response jsonb,
  error_message text,
  human_label text
    check (human_label in ('safe','unsafe','unsure')),
  human_notes text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.post_moderation_results enable row level security;
revoke all on public.post_moderation_results from anon;
grant select, update on public.post_moderation_results to authenticated;

drop policy if exists "Post admins can read moderation"
on public.post_moderation_results;

create policy "Post admins can read moderation"
on public.post_moderation_results
for select
to authenticated
using (public.has_admin_permission('manage_posts'::text));

drop policy if exists "Post admins can review moderation"
on public.post_moderation_results;

create policy "Post admins can review moderation"
on public.post_moderation_results
for update
to authenticated
using (public.has_admin_permission('manage_posts'::text))
with check (public.has_admin_permission('manage_posts'::text));
