-- AlumniConnections - Admin RBAC + Feedback Center
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- La fuente real de permisos administrativos es public.admin_permissions.
-- profiles.role se conserva solo como dato de presentación/compatibilidad.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) PERMISOS ADMINISTRATIVOS
-- =========================================================

create table if not exists public.admin_permissions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  manage_feedback boolean not null default false,
  manage_users boolean not null default false,
  manage_posts boolean not null default false,
  manage_events boolean not null default false,
  view_stats boolean not null default false,
  manage_admins boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_permissions enable row level security;

create or replace function public.alumni_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_admin_permissions_updated_at on public.admin_permissions;
create trigger trg_admin_permissions_updated_at
before update on public.admin_permissions
for each row execute function public.alumni_set_updated_at();

create or replace function public.is_alumni_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_permissions ap
    where ap.user_id = auth.uid()
  );
$$;

create or replace function public.has_admin_permission(p_permission text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select case p_permission
      when 'admin' then true
      when 'manage_feedback' then ap.manage_feedback
      when 'manage_users' then ap.manage_users
      when 'manage_posts' then ap.manage_posts
      when 'manage_events' then ap.manage_events
      when 'view_stats' then ap.view_stats
      when 'manage_admins' then ap.manage_admins
      else false
    end
    from public.admin_permissions ap
    where ap.user_id = auth.uid()
  ), false);
$$;

create or replace function public.get_my_admin_access()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select jsonb_build_object(
        'is_admin', true,
        'manage_feedback', ap.manage_feedback,
        'manage_users', ap.manage_users,
        'manage_posts', ap.manage_posts,
        'manage_events', ap.manage_events,
        'view_stats', ap.view_stats,
        'manage_admins', ap.manage_admins
      )
      from public.admin_permissions ap
      where ap.user_id = auth.uid()
    ),
    jsonb_build_object(
      'is_admin', false,
      'manage_feedback', false,
      'manage_users', false,
      'manage_posts', false,
      'manage_events', false,
      'view_stats', false,
      'manage_admins', false
    )
  );
$$;

grant execute on function public.is_alumni_admin() to authenticated;
grant execute on function public.has_admin_permission(text) to authenticated;
grant execute on function public.get_my_admin_access() to authenticated;

-- Permite leer permisos a administradores.
-- Ningún usuario puede INSERT/UPDATE/DELETE directamente en esta tabla.
drop policy if exists "Admins can read admin permissions" on public.admin_permissions;
create policy "Admins can read admin permissions"
on public.admin_permissions
for select
to authenticated
using (public.is_alumni_admin());

-- =========================================================
-- 2) AUDITORÍA DE CAMBIOS ADMINISTRATIVOS
-- =========================================================

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

drop policy if exists "Privileged admins can read audit log" on public.admin_audit_log;
create policy "Privileged admins can read audit log"
on public.admin_audit_log
for select
to authenticated
using (
  public.has_admin_permission('manage_admins')
  or public.has_admin_permission('view_stats')
);

-- =========================================================
-- 3) RPC SEGURA PARA DAR / QUITAR ADMIN Y PERMISOS
-- =========================================================

create or replace function public.set_admin_access(
  p_target_user_id uuid,
  p_is_admin boolean,
  p_manage_feedback boolean default false,
  p_manage_users boolean default false,
  p_manage_posts boolean default false,
  p_manage_events boolean default false,
  p_view_stats boolean default false,
  p_manage_admins boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_admin_permission('manage_admins') then
    raise exception 'No tienes permiso para administrar roles.';
  end if;

  if p_target_user_id = auth.uid() and p_is_admin = false then
    raise exception 'No puedes quitarte tu propio acceso administrativo.';
  end if;

  if not exists (select 1 from public.profiles where id = p_target_user_id) then
    raise exception 'El usuario indicado no existe.';
  end if;

  if p_is_admin then
    insert into public.admin_permissions (
      user_id,
      manage_feedback,
      manage_users,
      manage_posts,
      manage_events,
      view_stats,
      manage_admins
    )
    values (
      p_target_user_id,
      p_manage_feedback,
      p_manage_users,
      p_manage_posts,
      p_manage_events,
      p_view_stats,
      p_manage_admins
    )
    on conflict (user_id) do update set
      manage_feedback = excluded.manage_feedback,
      manage_users = excluded.manage_users,
      manage_posts = excluded.manage_posts,
      manage_events = excluded.manage_events,
      view_stats = excluded.view_stats,
      manage_admins = excluded.manage_admins,
      updated_at = now();

    -- Compatibilidad visual con el sistema administrativo existente.
    update public.profiles
    set role = 'admin'
    where id = p_target_user_id;
  else
    delete from public.admin_permissions
    where user_id = p_target_user_id;

    update public.profiles
    set role = 'user'
    where id = p_target_user_id;
  end if;

  insert into public.admin_audit_log (
    actor_user_id,
    target_user_id,
    action,
    details
  )
  values (
    auth.uid(),
    p_target_user_id,
    case when p_is_admin then 'admin_access_updated' else 'admin_access_revoked' end,
    jsonb_build_object(
      'is_admin', p_is_admin,
      'manage_feedback', p_manage_feedback,
      'manage_users', p_manage_users,
      'manage_posts', p_manage_posts,
      'manage_events', p_manage_events,
      'view_stats', p_view_stats,
      'manage_admins', p_manage_admins
    )
  );
end;
$$;

grant execute on function public.set_admin_access(
  uuid, boolean, boolean, boolean, boolean, boolean, boolean, boolean
) to authenticated;

-- Si ya existían perfiles con role='admin', se importan con permisos completos
-- para no bloquear el panel actual.
insert into public.admin_permissions (
  user_id,
  manage_feedback,
  manage_users,
  manage_posts,
  manage_events,
  view_stats,
  manage_admins
)
select
  p.id,
  true, true, true, true, true, true
from public.profiles p
where lower(coalesce(p.role, '')) = 'admin'
on conflict (user_id) do nothing;

-- =========================================================
-- 4) FEEDBACK DE TESTERS
-- =========================================================

create table if not exists public.feedback_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'bug'
    check (type in ('bug', 'ui', 'suggestion', 'missing_feature', 'other')),
  title text not null,
  description text not null,
  expected_behavior text,
  steps_to_reproduce text,
  source_path text,
  platform text,
  app_version text,
  priority text not null default 'medium'
    check (priority in ('low', 'medium', 'high', 'blocker')),
  status text not null default 'new'
    check (status in ('new', 'reviewing', 'resolved', 'closed')),
  attachments text[] not null default '{}'::text[],
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.feedback_reports enable row level security;

drop trigger if exists trg_feedback_reports_updated_at on public.feedback_reports;
create trigger trg_feedback_reports_updated_at
before update on public.feedback_reports
for each row execute function public.alumni_set_updated_at();

drop policy if exists "Users can create own feedback" on public.feedback_reports;
create policy "Users can create own feedback"
on public.feedback_reports
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can read own feedback" on public.feedback_reports;
create policy "Users can read own feedback"
on public.feedback_reports
for select
to authenticated
using (
  user_id = auth.uid()
  or public.has_admin_permission('manage_feedback')
);

drop policy if exists "Feedback admins can update feedback" on public.feedback_reports;
create policy "Feedback admins can update feedback"
on public.feedback_reports
for update
to authenticated
using (public.has_admin_permission('manage_feedback'))
with check (public.has_admin_permission('manage_feedback'));

-- =========================================================
-- 5) STORAGE PRIVADO PARA CAPTURAS
-- =========================================================

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'feedback',
  'feedback',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can upload own feedback files" on storage.objects;
create policy "Users can upload own feedback files"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'feedback'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users and feedback admins can read feedback files" on storage.objects;
create policy "Users and feedback admins can read feedback files"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'feedback'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.has_admin_permission('manage_feedback')
  )
);

drop policy if exists "Users and feedback admins can delete feedback files" on storage.objects;
create policy "Users and feedback admins can delete feedback files"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'feedback'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.has_admin_permission('manage_feedback')
  )
);

-- =========================================================
-- 6) VERIFICACIÓN
-- =========================================================

select
  p.username,
  p.role,
  ap.manage_feedback,
  ap.manage_users,
  ap.manage_posts,
  ap.manage_events,
  ap.view_stats,
  ap.manage_admins
from public.profiles p
left join public.admin_permissions ap on ap.user_id = p.id
order by p.created_at desc;
